auth:
  existingSecret: mariadb-secret
  username: user
  database: database

primary:
  service:
    type: ClusterIP

  readinessProbe:
    exec:
      command:
        - /bin/bash
        - -ec
        - mariadb-admin ping -uroot -p"${MARIADB_ROOT_PASSWORD:-}"
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 6

  livenessProbe:
    exec:
      command:
        - /bin/bash
        - -ec
        - mariadb-admin status -uroot -p"${MARIADB_ROOT_PASSWORD:-}"
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 6
