additionalArguments:
  - "--entryPoints.web.address=:80"   # ← Traefik이 직접 80포트를 열게 함
  - "--entryPoints.websecure.address=:443"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--providers.kubernetescrd"
  - "--accesslog=true"

service:
  type: NodePort   # NodePort 또는 LoadBalancer가 필요 없음
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30433


#hostNetwork: true   # ← Pod가 Node의 네트워크 직접 사용 (그래야 80 포트 바인딩 가능)
hostNetwork: false   # ← Pod가 Node의 네트워크 직접 사용 (그래야 80 포트 바인딩 가능)

ports:
  web:
    port: 80
    protocol: TCP
  websecure:
    port: 443
    protocol: TCP

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE

providers:
  kubernetesCRD:
    enabled: true
    namespace:
      - msa
  kubernetesIngress:
    enabled: false

rbac:
  enabled: true

log:
  level: DEBUG

accessLog:
  enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"