# values.yaml

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--providers.kubernetescrd"
  - "--accesslog=true"

ports:
  web:
    port: 80
    protocol: TCP

service:
  type: LoadBalancer
  externalIPs:
    - 10.0.0.38


providers:
  kubernetesCRD:
    enabled: true
    namespace:
      - msa
  kubernetesIngress:
    enabled: false

rbac:
  enabled: true

log:
  level: DEBUG

accessLog:
  enabled: true

resources:
  requests:
    cpu: "100m"   # 최소 보장 0.1 CPU
    memory: "128Mi"  # 최소 보장 128MiB
  limits:
    cpu: "500m"   # 최대 0.5 CPU
    memory: "512Mi"  # 최대 512MiB

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"