additionalArguments:
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--providers.kubernetescrd"
  - "--accesslog=true"

ports:
  web:
    port: 80
    targetPort: 80
#    expose:
#      exposedPort: 80
    protocol: TCP

service:
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
    namespace:
      - msa
  kubernetesIngress:
    enabled: true

rbac:
  enabled: true

log:
  level: DEBUG

accessLog:
  enabled: true