auth:
  existingSecret: mariadb-secret
  username: user
  database: database

primary:
  service:
    type: ClusterIP

  persistence:
    storageClass: local-path

secondary:
  persistence:
    storageClass: local-path