auth:
  existingSecret: mariadb-secret
  username: user
  database: database

primary:
  service:
    type: ClusterIP

  # TODO: 활성화 시켜야함
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false