clusterId: "kraft-cluster-id-01"

controller:
  replicaCount: 1
  quorumVoters: "0@kafka-controller-0.kafka-controller-headless.msa.svc.cluster.local:9093"
  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

broker:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi
  controllerConnection:
    quorumVoters: "0@kafka-controller-0.kafka-controller-headless.msa.svc.cluster.local:9093"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092
    name: CLIENT
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
    name: INTERNAL
  controller:
    protocol: PLAINTEXT
    containerPort: 9093
    name: CONTROLLER

extraEnvVars:
  - name: ALLOW_PLAINTEXT_LISTENER
    value: "yes"
