{{- $name := .Chart.Name -}}
{{- $port := .Values.service.port -}}
{{- range $i := until .Values.replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%d" $name $i }}
  labels:
    app: {{ $name }}
    podOrdinal: "{{ $i }}"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-%d" $name $i }}
  ports:
    - name: game
      port: {{ $port }}
      targetPort: {{ $port }}

---
{{- end }}
