apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
          effect: NoSchedule
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: USER_DB_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: USER_REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: USER_REDIS_PORT
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: KAFKA_BROKER
            - name: AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: AUTH_SERVER_URL
            - name: FASTIFY_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: FASTIFY_LOG_LEVEL
            - name: FILE_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: FILE_SERVER_URL
            - name: FASTIFY_PORT
              value: "{{ .Values.service.port }}"
