apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: CHAT_DB_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: CHAT_REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: CHAT_REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: JWT_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: JWT_REFRESH_EXPIRES_IN
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: KAFKA_BROKER
            - name: USER_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.SECRET_NAME }}
                  key: USER_SERVER_URL
            - name: FASTIFY_PORT
              value: "{{ .Values.service.port }}"
