provisionDataStore:
  cassandra: false
  elasticsearch: false

storage:
  type: elasticsearch
  elasticsearch:
    host: elasticsearch-master.monitor.svc  # 인증서에 유효한 이름으로 변경
    port: 9200
    scheme: https
    user: elastic
    password: RtHANpHt6xdCIG2y
    tls:
      enabled: true  # true로 변경
      secretName: es-tls-secret
      mountPath: /es-tls/ca-cert.pem
      subPath: ca-cert.pem
      ca: /es-tls/ca-cert.pem

collector:
  enabled: true
  service:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318

query:
  enabled: true

agent:
  enabled: false
