dbUser:
  existingSecret:
    name: cassandra-admin-auth
    namespace: monitor


resourcesPreset: "large"

persistence:
  storageClass: local-path
  size: 6Gi


livenessProbe:
  initialDelaySeconds: 240
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 30
  failureThreshold: 5