config:
  exporters:
    otlp:
      endpoint: jaeger-collector.monitor.svc.cluster.local:4317
      tls:
        insecure: false
  extensions:
    health_check: { }
  processors: # batch처리하고, 메모리사용 제한을 두는 memory_limiter를 사용
    batch: { }
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers:
          - otlp
          - jaeger
          - zipkin
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlp
