dbUser:
  existingSecret:
    name: cassandra-admin-auth
    namespace: monitor


resourcesPreset: "none"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"