apiVersion: v1
kind: Secret
metadata:
  name: user-server-secret
  namespace: msa
type: Opaque
stringData:
  DB_URL: "mysql://user:userpassword@mariadb-user.msa.svc.cluster.local:3306/database"
  REDIS_HOST: "redis-user-master.msa.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKER: "kafka.msa.svc.cluster.local:9092"
