# helm/mariadb-auth/values.yaml
auth:
  existingSecret: mariadb-secret
  username: user
  database: database

primary:
  service:
    type: ClusterIP

livenessProbe:
  enabled: true
  command:
    - /bin/bash
    - -ec
    - |
      exec mysqladmin status -u"$MARIADB_USER" -p"$MARIADB_PASSWORD"
readinessProbe:
  enabled: true
  command:
    - /bin/bash
    - -ec
    - |
      exec mysqladmin status -u"$MARIADB_USER" -p"$MARIADB_PASSWORD"
